#  component=catalogue
#    schema_type=mongodb
#    source common.sh
#
#    func_nodejs
#
#

- name : Catalogue Setup
  hosts: all
  become: yes
  vars:
   component: catalogue
   Scheme : mongodb
  tasks:
     name: NodeJs Setup
     ansible.builtin.import_tasks: nodejs.yml